name: Build all driver samples
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'
jobs:
  build:
    name: Build driver samples
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Retrieve and build all available solutions
        run: |
          Invoke-WebRequest -Uri 'https://marketplace.visualstudio.com/_apis/public/gallery/publishers/DriverDeveloperKits-WDK/vsextensions/WDKVsix/10.0.26100.0/vspackage?targetPlatform=5e3e564c-03bb-4499-8ae5-b2b35e9a86dc' -OutFile wdk.vsix
          & "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe" /f ".\wdk.vsix"
          # .\Build-AllSamples.ps1 -Verbose
          # Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
          # winget -v
          # winget list
          # & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        env:
          WDS_Configuration: ${{ matrix.configuration }}
          WDS_Platform: ${{ matrix.platform }}
          WDS_ReportFileName: _overview.${{ matrix.configuration }}.${{ matrix.platform }}

      - name: Archive build logs and overview build reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs
          path: _logs

  report:
    name: Generate global report
    runs-on: windows-2022
    needs: build
    if: always()
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Retrieve overview reports
        uses: actions/download-artifact@v3
        with:
          name: logs
          path: _logs

      - name: Join and generate global reports
        run: |
          .\.github\scripts\Join-CsvReports.ps1

      - name: Archive global overview build reports
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: _logs/_overview.all.*
